---
title: "charts"
author: "Volodymyr Lut"
date: "12/25/2019"
output: pdf_document
---

```{r}
data <- read.csv(file="logs.csv")
```

```{r}
library(ggplot2)
```

```{r}
gaussian <- data[data['controller'] == "gaussian",]
classic <- data[data['controller'] == "classic",]
l <- nrow(gaussian)
for(i in c(1:l)){
  data_iter_g <- as.numeric(unlist(strsplit(as.character(gaussian[i,]$action), '\\-')))
  data_iter_g <- data.frame(val = data_iter_g)
  data_iter_c <- as.numeric(unlist(strsplit(as.character(classic[i,]$action), '\\-')))
  data_iter_c <- data.frame(val = data_iter_c)
  data_iter_g$random <- if (gaussian[i,]$random == 1) "red" else "blue"
  data_iter_c$random <- if (classic[i,]$random == 1) "red" else "blue"
 bar_gaussian <- ggplot() + geom_bar(data = data_iter_g, aes(y=val, x=c("K1", "F1", "K2", "F2", "K3", "F3", "K4", "F4"), fill=random), stat="identity") + ylim(0, 64) + ggtitle(paste("Gaussian CNN for ", toupper(gaussian[i,]$dataset))) + xlab("Actions") + theme(legend.position = "none")
bar_classic <- ggplot() + geom_bar(data = data_iter_c, aes(y=val, x=c("K1", "F1", "K2", "F2", "K3", "F3", "K4", "F4"), fill=random), stat="identity") + ylim(0, 64) + ggtitle(paste("Classic CNN for ", toupper(classic[i,]$dataset))) + xlab("Actions") + theme(legend.position = "none")
line_gaussian <- ggplot() + geom_smooth(data = head(gaussian, i), aes(y=accuracy, x=c(0:(i-1)))) + xlim(0, l) + ggtitle(paste("Gaussian accuracy for ", toupper(gaussian[i,]$dataset))) + xlab("Epoch")
line_classic <- ggplot() + geom_smooth(data = head(classic, i), aes(y=accuracy, x=c(0:(i-1)))) + xlim(0, l) + ggtitle(paste("Classic accuracy for ", toupper(classic[i,]$dataset))) + xlab("Epoch")
  ggarrange(bar_gaussian, bar_classic, line_gaussian, line_classic, ncol = 2, nrow = 2)
  ggsave(paste(paste("img/", i), ".png"))
}
```
