---
title: "charts"
author: "Volodymyr Lut"
date: "12/25/2019"
output: pdf_document
---

```{r}
data <- read.csv(file="logs.csv")
```

```{r}
library(ggplot2)
library(ggpubr)
```

```{r}
gaussian <- data[data['controller'] == "gaussian",]
classic <- data[data['controller'] == "classic",]
gaussian_ucb <- data_ucb[data_ucb['controller'] == "gaussian",]
classic_ucb <- data_ucb[data_ucb['controller'] == "classic",]
i <- nrow(gaussian)
l <- nrow(classic)
#l <- nrow(gaussian_ucb)
line_gaussian <- ggplot() + geom_smooth(data = gaussian, aes(y=total_reward, x=c(0:(i-1)))) + xlim(0, l) + ggtitle("Gaussian total reward EG") + xlab("Epoch")
line_classic <- ggplot() + geom_smooth(data = classic, aes(y=total_reward, x=c(0:(i-1)))) + xlim(0, l) + 
ggtitle("Classic total_reward EG") + xlab("Epoch")



  ggarrange(line_gaussian, line_classic,  ncol = 1, nrow = 2)
  ggsave("total_reward_epsilon_greedy.png")
```
```{r}
gaussian <- data[data['controller'] == "gaussian",]
classic <- data[data['controller'] == "classic",]
l <- nrow(gaussian)
line_gaussian <- ggplot() + geom_smooth(data = gaussian, aes(y=accuracy, x=c(0:(i-1)))) + xlim(0, l) + ggtitle("Gaussian accuracy") + xlab("Epoch")
line_classic <- ggplot() + geom_smooth(data = classic, aes(y=accuracy, x=c(0:(i-1)))) + xlim(0, l) + ggtitle("Classic accuracy") + xlab("Epoch")
  ggarrange(line_gaussian, line_classic, ncol = 1, nrow = 2)
  ggsave("ucb.png")
```
```{r}
gaussian <- data[data['controller'] == "gaussian",]
gaussian$known_action <- duplicated(gaussian$action)
classic$known_action <- duplicated(classic$action)
l <- nrow(gaussian)
line_gaussian <- ggplot(gaussian, aes(y=accuracy, x=c(0:(i-1)), color=known_action)) + geom_area() + xlim(0, l) + ggtitle("Accuracy by nature of the action") +xlab("Epoch")
line_classic <- ggplot(classic, aes(y=accuracy, x=c(0:(i-1)), color=known_action)) + geom_area() + xlim(0, l) + ggtitle("MLE variance") +xlab("Epoch")
ggarrange(line_gaussian, line_classic, ncol = 1, nrow = 2)
ggsave("action_unique.png")
```

```{r}
p1 <- ggplot(data = data.frame(x = c(-1, 1)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = gaussian[20,]$mu, sd = sqrt(gaussian[20,]$sigma))) + xlab("20 epochs") + ylab("") +
  scale_y_continuous(breaks = NULL)
p2 <- ggplot(data = data.frame(x = c(-1, 1)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = gaussian[40,]$mu, sd = sqrt(gaussian[40,]$sigma))) + xlab("40 epochs") + ylab("") +
  scale_y_continuous(breaks = NULL)
p3 <- ggplot(data = data.frame(x = c(-1, 1)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = gaussian[60,]$mu, sd = sqrt(gaussian[60,]$sigma))) + xlab("60 epochs") + ylab("") +
  scale_y_continuous(breaks = NULL)
p4 <- ggplot(data = data.frame(x = c(-1, 1)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = gaussian[80,]$mu, sd = sqrt(gaussian[80,]$sigma))) + xlab("80 epochs") + ylab("") +
  scale_y_continuous(breaks = NULL)
p5 <- ggplot(data = data.frame(x = c(-1, 1)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = gaussian[100,]$mu, sd = sqrt(gaussian[100,]$sigma))) + xlab("100 epochs") + ylab("") +
  scale_y_continuous(breaks = NULL)
p6 <- ggplot(data = data.frame(x = c(-1, 1)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = gaussian[120,]$mu, sd = sqrt(gaussian[120,]$sigma))) + xlab("120 epochs") + ylab("") +
  scale_y_continuous(breaks = NULL)
ggarrange(p1, p2, p3, p4, p5, p6, ncol = 3, nrow = 2)
ggsave("musigma.png")
```